### PR TITLE
add Irina Rish as speaker

### PR DESCRIPTION
**Pull request by liellnima**

### CODE REVIEW

**Review by etiennecollin — COMMENTED** [review]
Everything seems good to me. I corrected a typo and updated the next speaker in `/_data/settings.yml`.

**Review by etiennecollin — APPROVED** [review]

**Review by alexhernandezgarcia — APPROVED** [review]
Looks good! I would like to confirm the talk of Irina's talk (currently 4 pm UTC = 11 am ET)

**Comment by liellnima** [comment]
time is confirmed, I also added title and abstract

**Comment by liellnima** [comment]
please merge when approved

**Review by alexhernandezgarcia — APPROVED** [review]
Cool, will merge to announce on Twitter!

**Pull request merged**
