### PR TITLE
Updates to schedule and speakers

### PR DESCRIPTION
**Pull request by alexhernandezgarcia**

### CODE REVIEW

**Comment by liellnima** [comment]
Thank you! 
Question: Do I get that right that the skip tag is only there to make sure the same speakers are not several times on the speaker page? (i.e. we cannot assign both an in-person event & online event to the same person).

Everything looks fine to me - just the times need to be adapted. (I'll do that)

**Review by liellnima — CHANGES_REQUESTED** [review]
Uuuh, I am learning - so here I can submit a review!

Same as in the comment:

Question: Do I get that right that the skip tag is only there to make sure the same speakers are not several times on the speaker page? (i.e. we cannot assign both an in-person event & online event to the same person).

Everything looks fine to me - just the times need to be adapted. (I'll do that)

**Review by liellnima — APPROVED** [review]
Sorry, times were already correct, I was not aware it's UTC time! Schedule looks great!

**Comment by alexhernandezgarcia** [comment]
@liellnima 

skip tag: yeah, that's it. It's a bit of a patch solution, not very elegant, but it does the job. If I have time, I'll code something better.

**Pull request merged**
