### PR TITLE
Update donation bar

### PR DESCRIPTION
**Pull request by liellnima**
Target: 50k, to make it more approachable (agreed upon in team meeting)

### CODE REVIEW

**Comment by liellnima** [comment]
please go ahead and merge if you approve it!

**Review by alexhernandezgarcia — CHANGES_REQUESTED** [review]
I believe the target is specified in `_data/settings.yml`, right @etiennecollin ?

**Comment by etiennecollin** [comment]
On the current main branch, the target is specified in `_data/settings.yml`. The current value is automatically updated using the google sheet whose URL is also specified in the settings.yml file. We can simply update the target and targetText in the file instead of creating a new donations file.

**Comment by etiennecollin** [comment]
We should be good to merge.

**Review by etiennecollin — CHANGES_REQUESTED** [review]
No need for this. Check conversation!

**Pull request merged**
